services:
  - type: web
    name: gifts-backend
    env: node
    plan: free
    rootDir: apps/backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: BACKEND_TOKEN
        sync: false
      - key: DATA_DIR
        value: ./data